name: Auto sync

on: 
  workflow_dispatch:
  schedule:
  - cron: "0 0/4 * * ? *"

jobs:
sync:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v4

  - name: Auto sync your fork upstream
 
  uses: rovast/sync-upstream-repo@v0.0.1
  with:
    
    upstream_repo: https://github.com/ColomboRiccardo/Pratica-Git-per-Epicode
    
    upstream_branch: main
    
    downstream_branch: main 
    # GitHub Bot token
    token: ${{ secrets.GITHUB_TOKEN }}
